[package]
name = "yfin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
structopt = { version = "0.3", default-features = false }
spinners = "2.0.0"
